[package]
name = "evo-rust-backend"
version = "0.1.0"
authors = ["Anton Kuzmin <sassanid18@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.18"
scraper = "0.11.0"
selectors = "0.21.0"
